service: click-funnel-lambda

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  stage: development
  region: us-east-1
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  environment:
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
    CLICK_FUNNEL_CONTACT_TABLE: "Contact"
    CLICK_FUNNEL_ORDER_TABLE: "Order"
    INFUSIONSOFT_API_NAME: ""
    INFUSIONSOFT_API_KEY: ""
    SIMPLY_BOOK_SERVICE_URL_lOGIN: "https://user-api.simplybook.me/login"
    SIMPLY_BOOK_SERVICE_URL: "https://user-api.simplybook.me/"
    SIMPLY_BOOK_ADMIN_SERVICE_URL: "https://user-api.simplybook.me/admin/"
    SIMPLY_BOOK_COMPANY_LOGIN: "phqviet93gmailcom"
    SIMPLY_BOOK_USER: "admin"
    SIMPLY_BOOK_PASSWORD: "12345678x@X"
    SIMPLY_BOOK_API_KEY: "4de2a2545aed8e5e19861ee91221460c7e7e0ec90bff6dcad96fcc4d68c8e228"
    SIMPLY_BOOK_SECRET_KEY: "c9c8476bdedc3a2294a5fc69c9d0019e2af44dbe126ccb10f7431739a720b1ef"
package:
    artifact: build/distributions/aws-java-clickfunnel-http-endpoint.zip

plugins:
#    - serverless-dynamodb-local
#    - serverless-offline
custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true

functions:
  createContact:
    handler: com.tq.clickfunnel.lambda.handler.InterceptorEventPayloadProxy
    description: Creating the new contact
    events: # All events associated with this function
      - http:
          path: contact?event=contact-created
          method: post
      - http:
          path: contact?event=contact-updated
          method: post
  createOrder:
    handler: com.tq.clickfunnel.lambda.handler.InterceptorEventPayloadProxy
    description: Creating the new Order
    events:
      - http:
          path: order?event=order-created
          method: post
  updateOrder:
    handler: com.tq.clickfunnel.lambda.handler.InterceptorEventPayloadProxy
    description: Updating the existing Order
    events:
      - http:
          path: order?event=order-updated
          method: post