package com.tq.simplybook.lambda.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "EventBook")
public class BookEvent {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private Long id;

    @DynamoDBAttribute(attributeName = "bookID")
    private Integer bookID;

    @DynamoDBAttribute(attributeName = "bookingHash")
    private String bookingHash;

    @DynamoDBAttribute(attributeName = "company")
    private String company;

    @DynamoDBAttribute(attributeName = "eventType")
    private String eventType;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getBookID() {
        return bookID;
    }

    public void setBookID(Integer bookID) {
        this.bookID = bookID;
    }

    public String getBookingHash() {
        return bookingHash;
    }

    public void setBookingHash(String bookingHash) {
        this.bookingHash = bookingHash;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getEventType() {
        return eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    @Override
    public String toString() {
        return "BookEvent [id=" + id + ", bookID=" + bookID + ", bookingHash=" + bookingHash + ", company=" + company + ", eventType="
                + eventType + "]";
    }
}
