package com.tq.clickfunnel.lambda.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson;

@DynamoDBTable(tableName = "Contact")
public class ContactItem {
    
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;
    
    @DynamoDBTypeConvertedJson
    @DynamoDBAttribute(attributeName ="client")
    private ClientInfo client;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public ClientInfo getClient() {
        return client;
    }

    public void setClient(ClientInfo client) {
        this.client = client;
    }
    
    public ContactItem withContactInfo(ClientInfo clientInfo) {
        this.client = clientInfo;
        return this;
    }

    @Override
    public String toString() {
        return "ContactItem [id=" + id + ", client=" + client + "]";
    }
}
