package com.tq.common.lambda.dynamodb.model;

import java.util.HashSet;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "LatestClinikoAppointment")
public class LatestClinikoAppointment {
	public static final String LATEST_UPDATED_KEY = "latest_update";
	private String latest_update = LATEST_UPDATED_KEY;
	private Set<Long> created = new HashSet<Long>();
	private Set<Long> removed = new HashSet<Long>();
	private String latest_update_time;
	private String checkIndex;
	private String apiKey;

	public LatestClinikoAppointment() {
		created.add(-1L);
		removed.add(-1L);
	}

	@DynamoDBHashKey(attributeName = "latest_update")
	public String getLatest_update() {
		return latest_update;
	}

	public void setLatest_update(String latest_update) {
		this.latest_update = latest_update;
	}

	@DynamoDBAttribute(attributeName = "created")
	public Set<Long> getCreated() {
		return created;
	}

	public void setCreated(Set<Long> created) {
		this.created = created;
	}

	@DynamoDBAttribute(attributeName = "removed")
	public Set<Long> getRemoved() {
		return removed;
	}

	public void setRemoved(Set<Long> removed) {
		this.removed = removed;
	}

	@DynamoDBAttribute(attributeName = "latest_update_time")
	public String getLatest_update_time() {
		return latest_update_time;
	}

	public void setLatest_update_time(String latest_update_time) {
		this.latest_update_time = latest_update_time;
	}

	@DynamoDBRangeKey(attributeName = "checkIndex")
	@DynamoDBAutoGeneratedKey
	public String getCheckIndex() {
		return checkIndex;
	}

	public void setCheckIndex(String checkIndex) {
		this.checkIndex = checkIndex;
	}

	@DynamoDBAttribute(attributeName = "apiKey")
	public String getApiKey() {
		return apiKey;
	}

	public void setApiKey(String apiKey) {
		this.apiKey = apiKey;
	}

	@Override
	public String toString() {
		return "LatestClinikoAppointment [latest_update=" + latest_update + ", created=" + created + ", removed="
				+ removed + ", latest_update_time=" + latest_update_time + ", checkIndex=" + checkIndex + ", apiKey="
				+ apiKey + "]";
	}

	public static boolean isDefaultSet(Set<Long> set) {
		return set.size() > 1 || (set.size() == 1 && !set.contains(-1L));
	}

	public LatestClinikoAppointment(Set<Long> created, Set<Long> removed, String latest_update_time, String apiKey) {
		this.created = created;
		this.removed = removed;
		this.latest_update_time = latest_update_time;
		this.apiKey = apiKey;
	}

}
